config/routes.rb
Rails.application.routes.draw do




  get 'cities/show'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
#affichage GET par défaut avec home methode ET page !!!
  root to: 'static_pages#home'

  #page statiques
  get 'static_pages/team'
  get 'static_pages/contact'

 
#route dynamique
  get 'firstname(/:var)' , to: 'static_pages#firstname', as: 'welcome' #création d'un nom pour le chemin


#route dynamique affichage GET nouveau gossip
# get 'gossip(/:id)', to: 'static_pages#gossip'   #deja crre par la ressource

#creation d 'un potin



resources :gossips, only: [ :create, :new, :show, :edit ]  do
  resources :comment
end
resources :users
resources :sessions, only: [:new, :create, :destroy]

end
 

app/models/add_login_user.rb
class AddLoginUser < ApplicationRecord
end

app/models/add_password_digest_user.rb
class AddPasswordDigestUser < ApplicationRecord
    has_secure_password
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user
    has_many :comments
    has_many :tags


validates :title, 
presence: true,
length: { in: 3..14 , wrong_length: " doit etre entre 3 et 14 caracteres"  }


validates :content, 
presence: true
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

    belongs_to :city
    has_many :Gossips  
    
    validates :first_name, 
    presence: true
    
    
    # validates :last_name, 
    # presence: true
    
    
    # validates :email, 
    # presence: true,
    # format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/,
    #     message: "format du mail a revoir" }



end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show

    @city = Cities.find_by_id(:id)


  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def new
    # page de creation du formulaire

    puts "$" * 60
    @gossip = Gossip.new
  end

  def create
 
    current_user = User.find_by_id(session[:current_user_id])

    begin 
    @gossip = Gossip.new(
      'title' => params[:title],
      'content' => params[:content],
      'user_id' =>  current_user.id)
     
        if @gossip.save
        puts "#ici#" *10
       
        flash[:gossip_success] = "😸youpi potin cree par #{@gossip.title}" 
     
        # redirect_to root_path  # repasse par le controleur
        render ('root_path') 

        else
            puts "#nopee#" *10
            flash[:gossip_alert] = "⚠️ Ragot non cree."
            render ('new')  #va en direct sur la view (garde les variables en memoire)
        end
    rescue Exception
      puts "#nopee#" *10
    end


  end

  def show
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    if @gossip.update(tes_params)
      redirect_to @gossip
    else
      render :edit
    end 
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  # cherche s'il existe un utilisateur en base avec l’e-mail
  user = User.find_by(email: params[:login])
puts "$"*20
puts params
puts "$"*20
  # on vérifie si l'utilisateur existe bien ET si on arrive à l'authentifier (méthode bcrypt) avec le mot de passe 
  
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        render file: './app/views/gossips/new.html.erb'

      else
        flash.now[:danger] = 'Invalid email/password combination'
        render 'new'
      end


  end

  
    def destroy
      session.delete(:user_id)
    end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
     #AFFICHER TOUT LES POTINS
  @list = Gossip.all
  end

#définition de la page team
def team
    
end

#définition de la page contact
def contact
  
end

#définition de la page welcome dynamique
  def welcome
    @first_name = params[:first_name]
    puts params[:first_name].inspect
  end

#définition de la page potin dynamique
  def gossip
    @gossips = Gossip.all
    @id = params[:id]
    puts "******************"
    puts @id
    puts "******************"
  end


#définition de la page auteur dynamique
def auteur
  @gossips = Gossip.all
  @title = params[:title]
end  


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # def index
  #   @users = User.all
  # end

  # def show
  #   @user = User.find(params[:id])
  # end

  def new
    @user = User.new
  end

  def create
    puts "*"*60
    @user = User.new(
      'first_name' => params[:first_name],
      'last_name' => params[:last_name],
      'city_id' => City.all.sample.id,
      'login' => params[:login],
      'password_digest' => params[:password],
      'email' => params[:email])

    
        if @user.save    
        flash[:user_success] = "😸youpi compte cree pour  #{@user.first_name}" 
     
         redirect_to root_path  # repasse par le controleur
        else
         render ('new_path') 
        end
    # user = User.create(post_params)   # post_params ???
    # redirect_to user_path(user.id)
  end

  # def edit
  #   @user = User.find(params[:id])
  # end

#   def update
#     @user = User.find(params[:id])
#     @user.update(post_params)
#     redirect_to users.path
#   end

#   def destroy
#     @user = User.find(params[:id])
#     @user.destroy
#     redirect_to users.path
#   end

#  private 
#  def post_params
#   # params.require(:user).permit(:name, :slug)
#   params.require(:user).permit(:first_name)
#  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/static_pages/auteur.htm.erb
<div class="container" style="height:80vh">
  <h1>Voici la page de l'auteur : <span style="color:#8064A2"><%= @title%></span> </h1>
  <h3 class="mb-5">Ses articles :</h3>

  <div class="container row justify-content-center">
    <% @gossips.each do |gossip| %>
      <% if gossip.title == @title%>
        <div class="card mb-3 mx-4 card-home" style="width: 18rem;">
          <div class="card-body">
            <p class="card-text"><em><%= gossip.content %></em></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <a href="<%= root_path %>" class="btn btn-primary mt-3 rounded-pill">👈 Revenir au menu</a>
</div>

app/views/static_pages/contact.html.erb
<div class="container" style="height:80vh">
<h1> comment nous joindre </h1>
<p> tel : xxx </p>
<p> mail : xxx </p>
</div>

app/views/static_pages/firstname.html.erb
<div class="container" style="height:80vh">
<p>Bonjour <%= params[:var] %> ! Ici c'est notre super site de potins, il est chouette, non ?</p>

</div>

app/views/static_pages/gossip.html.erb
<div class="container" style="height:80vh">

      <%  mygossip = Gossip.find(@id)%>
        <h3> <%= mygossip.title %></h3>
        <p> <em><%= mygossip.content %></em></p>
      
        <hr>
 
</div>

app/views/static_pages/home.html.erb
<div class="jumbotron">

<h1>bienvenu sur cette appli </h1>

<h2> 👋 pour rajouter un potin c'est ici :  </h2>
<a href="<%= new_gossip_path %>" class="btn btn-primary mt-3 rounded-pill">👈 ecrire un potin</a>
  </div>



  


<div class="jumbotron">
 <h2>  voici les derniers potins:  </h2>

<%  @list.each do |gossip| %>
<p class="card-text"><em><%= gossip.user.first_name %> à parler de  "<%= gossip.title %>"  </em></p>
<a href="gossips/<%=gossip.id%>" class="btn btn-primary">Voir le potin</a>
<a href="firstname/<%=gossip.id%>" class="btn btn-primary">Voir l'auteur'</a>
  <% end %>

  </div>

app/views/static_pages/team.html.erb
<div class="container" style="height:80vh">
<h1> voici l'equipe </h1>
<ul>
<li>Nell</li>
<li>Josselin</li>
<li>Sarah</li>
</ul>

</div>