config/routes.rb
Rails.application.routes.draw do




  get 'cities/show'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
#affichage GET par défaut avec home methode ET page !!!
  root to: 'static_pages#home'

  #page statiques
  get 'static_pages/team'
  get 'static_pages/contact'

 
#route dynamique
  get 'firstname(/:var)' , to: 'static_pages#firstname', as: 'welcome' #création d'un nom pour le chemin


#route dynamique affichage GET nouveau gossip
# get 'gossip(/:id)', to: 'static_pages#gossip'   #deja crre par la ressource

#creation d 'un potin



resources :gossips, only: [ :create, :new, :show, :edit ]  do
  resources :comment
end
resources :users
resources :sessions, only: [:new, :create, :destroy]

end
 

app/models/add_login_user.rb
class AddLoginUser < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user
    has_many :comments
    has_many :tags


validates :title, 
presence: true,
length: { in: 3..14 , wrong_length: " doit etre entre 3 et 14 caracteres"  }


validates :content, 
presence: true
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

    belongs_to :city
    has_many :Gossips  
    
    validates :first_name, 
    presence: true
    
    
    # validates :last_name, 
    # presence: true
    
    
    # validates :email, 
    # presence: true,
    # format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/,
    #     message: "format du mail a revoir" }



end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show

    @city = Cities.find_by_id(:id)


  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def new
    # page de creation du formulaire

    puts "$" * 60
    @gossip = Gossip.new
  end

  def create
 
    current_user = User.find_by_id(session[:current_user_id])

    begin 
    @gossip = Gossip.new(
      'title' => params[:title],
      'content' => params[:content],
      'user_id' =>  current_user.id)
     
        if @gossip.save
        puts "#ici#" *10
       
        flash[:gossip_success] = "😸youpi potin cree par #{@gossip.title}" 
     
        # redirect_to root_path  # repasse par le controleur
        render ('root_path') 

        else
            puts "#nopee#" *10
            flash[:gossip_alert] = "⚠️ Ragot non cree."
            render ('new')  #va en direct sur la view (garde les variables en memoire)
        end
    rescue Exception
      puts "#nopee#" *10
    end


  end

  def show
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    if @gossip.update(tes_params)
      redirect_to @gossip
    else
      render :edit
    end 
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  # cherche s'il existe un utilisateur en base avec l’e-mail
  user = User.find_by(email: params[:login])
puts "$"*20
puts params
puts "$"*20
  # on vérifie si l'utilisateur existe bien ET si on arrive à l'authentifier (méthode bcrypt) avec le mot de passe 
  
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        render file: './app/views/gossips/new.html.erb'

      else
        flash.now[:danger] = 'Invalid email/password combination'
        render 'new'
      end


  end

  
    def destroy
      session.delete(:user_id)
    end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # def index
  #   @users = User.all
  # end

  # def show
  #   @user = User.find(params[:id])
  # end

  def new
    @user = User.new
  end

  def create
    puts "*"*60
    @user = User.new(
      'first_name' => params[:first_name],
      'last_name' => params[:last_name],
      'city_id' => City.all.sample.id,
      'login' => params[:login],
      'password_digest' => params[:password],
      'email' => params[:email])

    
        if @user.save    
        flash[:user_success] = "😸youpi compte cree pour  #{@user.first_name}" 
     
         redirect_to root_path  # repasse par le controleur
        else
         render ('new_path') 
        end
    # user = User.create(post_params)   # post_params ???
    # redirect_to user_path(user.id)
  end

  # def edit
  #   @user = User.find(params[:id])
  # end

#   def update
#     @user = User.find(params[:id])
#     @user.update(post_params)
#     redirect_to users.path
#   end

#   def destroy
#     @user = User.find(params[:id])
#     @user.destroy
#     redirect_to users.path
#   end

#  private 
#  def post_params
#   # params.require(:user).permit(:name, :slug)
#   params.require(:user).permit(:first_name)
#  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>GossipProjetV3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

 
<div >THP PROJECT
</div>

<br>
  </head>

  <body>



 


<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
<!-- mes pages ici -->
<li class="nav-item active">

    <%= link_to "Home", root_path, class: "nav-link active" %>

    <li class="nav-item">

        <%= link_to "Equipe", static_pages_team_path, class: "nav-link active" %>

    </li>

    <li class="nav-item">
          <%= link_to "Contact", static_pages_contact_path,  class: "nav-link active" %>
    </li>
        <li class="nav-item">
          <%= link_to "creer un compte", new_user_path,  class: "nav-link active" %>
    </li>
 <li class="nav-item">
<%= link_to "Se déconnecter", session_path(session.id), method: :delete, class: "nav-link active" %>
</li>


<!-- fin de mes pages ici -->

     
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
       
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>

            </div>
          </li>
        </ul>



        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>



<% flash.each do |type, msg| %>
<div class="alert alert-info" role="alert">


    <%= msg %>
  </div>


<% end %>
<div class="jumbotron">
   <%= yield %> 
</div>


   <footer class="container">
      <p>© THP Winter 2022</p>
    </footer>
  </body>
</html>